#!/usr/bin/env ruby
require 'json'
require_relative '../../demo/lib/query_parser.rb'
require_relative '../../demo/lib/css_writer.rb'

# Generate a CSS file with rules for finding team members
class Generate
  def initialize
    @root = File.join(File.expand_path(File.dirname(__FILE__)), '../..')
    people = JSON.parse(File.open("#{@root}/demo/data/members.json").read)
    @people = people.map do |person|
      gravatar_url = person['gravatar_url']
      if !gravatar_url.nil?
        image = "#{person['gravatar_url']}%3Fs=300%26&d=https://www.algolia.com/static_assets/images/about-you.jpg"
        person['image'] = CSSWriter.cloudinary(image, fetch: true)
      else
        image = 'https://www.algolia.com/static_assets/images/' \
             "about-#{person['short_name']}.jpg"
        person['image'] = CSSWriter.cloudinary(image)
      end
      person
    end

    @synonyms = [
      { 'attribute' => 'name', 'original' => 'Paul-Louis Nech', 'replace' => 'PLN' },
      { 'attribute' => 'name', 'original' => 'Rémy-Christophe Schermesser', 'replace' => 'RCS' },
      { 'attribute' => 'name', 'original' => 'Rémy-Christophe Schermesser', 'replace' => 'Scala Schermesser' },
      { 'attribute' => 'name', 'original' => 'Gianluca Bargelli', 'replace' => 'Pizza Master Bargelli' },
      { 'attribute' => 'name', 'original' => 'Gianluca Bargelli', 'replace' => 'Proudlygeek' },
      { 'attribute' => 'name', 'original' => 'Jan Petr', 'replace' => 'Honza' },
      { 'attribute' => 'name', 'original' => 'Clément Leprovost', 'replace' => 'Grumpy Leprovost' },
      { 'attribute' => 'name', 'original' => 'Matthieu Dumont', 'replace' => 'Jerska' },
      { 'attribute' => 'name', 'original' => 'Julien Lemoine', 'replace' => 'Speedblue' },
      { 'attribute' => 'name', 'original' => 'Sylvain Utard', 'replace' => 'Redox' },
      { 'attribute' => 'name', 'original' => 'Kevin Granger', 'replace' => 'Shipow' },
      { 'attribute' => 'name', 'original' => 'Josh Dzielak', 'replace' => 'Dzello' },
      { 'attribute' => 'name', 'original' => 'Alexandre Collin', 'replace' => 'Seafoox' },
      { 'attribute' => 'name', 'original' => 'Alexandre Stanislawski', 'replace' => 'Bobylito' },
      { 'attribute' => 'name', 'original' => 'Vincent Voyer', 'replace' => 'Vvo' },
      { 'attribute' => 'name', 'original' => 'Maxime Locqueville', 'replace' => 'Maxiloc' },
      { 'attribute' => 'name', 'original' => 'Marion Aguirre', 'replace' => 'Minerva McGonagall' },
      { 'attribute' => 'name', 'original' => 'Emily Hayman', 'replace' => 'Flexbox girl' },
      { 'attribute' => 'name', 'original' => 'Tim Carry', 'replace' => 'pixelastic' },
      { 'attribute' => 'name', 'original' => 'Antoine Gauvain', 'replace' => 'drlkf' },
      { 'attribute' => 'role', 'original' => 'Solutions Engineer', 'replace' => 'SE' }
    ]
  end

  def run
    lookup_table = QueryParser.empty_query(@people, %w(name role))
    @people.each do |person|
      matches = [
        { attribute: 'name', keyword: person['name'] },
        { attribute: 'role', keyword: person['role'] }
      ]

      entry_table = QueryParser.index(person, matches: matches)
      lookup_table = QueryParser.merge(lookup_table, entry_table)
    end

    lookup_table = QueryParser.uniq(lookup_table)
    lookup_table = QueryParser.add_synonyms(lookup_table, @people, @synonyms)
    lookup_table = QueryParser.add_typos(lookup_table)
    lookup_table = QueryParser.uniq(lookup_table)

    options = {
      custom_ranking: 'order',
      searchable_attributes: %w(name role)
    }
    lookup_table = QueryParser.sort(lookup_table, options)

    facets = QueryParser.generate_facets(lookup_table, 'team', @people)

    css = CSSWriter.base
    css = CSSWriter.add_facets(css, facets, @people, lookup_table)
    css = CSSWriter.add_results(css, lookup_table)

    main_css = File.read("#{@root}/demo/public/css/base.css")
    final_css = main_css + css.join("\n")

    File.write("#{@root}/demo/public/css/search.css", final_css)
  end
end
Generate.new.run
