#!/usr/bin/env sh
set -eu

# Creating tmp dir to push to gh-pages branch
mkdir -p ./gh-pages
rm -rf ./gh-pages/*

# Building website
cd ./website
yarn upgrade algolia-frontend-components
node ./buildComponents.js
middleman build
mv -fun ./build/* ../gh-pages
rm ../gh-pages/images/.keep

# Copying the demo
cd ../gh-pages
mkdir ./demo
cp -r ../demo/public/* ./demo
