#!/usr/bin/env sh
set -eu

# Creating tmp dir to push to gh-pages branch
mkdir -p ./gh-pages
rm -rf ./gh-pages/*

yarn upgrade algolia-frontend-components

# Building website
cd ./website
node ./buildComponents.js
middleman build
mv -fn ./build/* ../gh-pages
rm ../gh-pages/images/.keep

# Copying the demo
cd ../gh-pages
mkdir ./demo
cp -r ../demo/public/* ./demo
