#!/usr/bin/env ruby
require 'json'
require_relative '../lib/query_parser.rb'
require_relative '../lib/css_writer.rb'

# Generate a CSS file with rules for finding team members
class Generate
  def initialize(args)
    @with_typos = args.include?('--with-typos')
    @with_facets = args.include?('--with-facets')
    @with_roles = args.include?('--with-roles')

    @root = File.join(File.expand_path(File.dirname(__FILE__)), '..')
    people = JSON.parse(File.open("#{@root}/data/members.json").read)
    @people = people.map do |person|
      if person.key? 'gravatar_url'
        image = "#{person['gravatar_url']}%3Fs=300%26&d=https://www.algolia.com/static_assets/images/about-you.jpg"
        person['image'] = CSSWriter.cloudinary(image, fetch: true)
      else
        image = 'https://www.algolia.com/static_assets/images/' \
             "about-#{person['short_name']}.jpg"
        person['image'] = CSSWriter.cloudinary(image)
      end
      person
    end

    @synonyms = [
      { 'attribute' => 'name', 'original' => 'Paul-Louis Nech', 'replace' => 'PLN' },
      { 'attribute' => 'name', 'original' => 'Rémy-Christophe Schermesser', 'replace' => 'RCS' },
      { 'attribute' => 'name', 'original' => 'Rémy-Christophe Schermesser', 'replace' => 'Scala Schermesser' },
      { 'attribute' => 'name', 'original' => 'Gianluca Bargelli', 'replace' => 'Pizza Master Bargelli' },
      { 'attribute' => 'name', 'original' => 'Gianluca Bargelli', 'replace' => 'Proudlygeek' },
      { 'attribute' => 'name', 'original' => 'Jan Petr', 'replace' => 'Honza' },
      { 'attribute' => 'name', 'original' => 'Matthieu Dumont', 'replace' => 'Jerska' },
      { 'attribute' => 'name', 'original' => 'Julien Lemoine', 'replace' => 'Speedblue' },
      { 'attribute' => 'name', 'original' => 'Sylvain Utard', 'replace' => 'Redox' },
      { 'attribute' => 'name', 'original' => 'Kevin Granger', 'replace' => 'Shipow' },
      { 'attribute' => 'name', 'original' => 'Josh Dzielak', 'replace' => 'Dzello' },
      { 'attribute' => 'name', 'original' => 'Alexandre Collin', 'replace' => 'Seafoox' },
      { 'attribute' => 'name', 'original' => 'Alexandre Stanislawski', 'replace' => 'Bobylito' },
      { 'attribute' => 'name', 'original' => 'Vincent Voyer', 'replace' => 'Vvo' },
      { 'attribute' => 'name', 'original' => 'Maxime Locqueville', 'replace' => 'Maxiloc' },
      { 'attribute' => 'name', 'original' => 'Marion Aguirre', 'replace' => 'Minerva McGonagall' },
      { 'attribute' => 'name', 'original' => 'Emily Hayman', 'replace' => 'Flexbox girl' },
      { 'attribute' => 'name', 'original' => 'Tim Carry', 'replace' => 'pixelastic' },
      { 'attribute' => 'name', 'original' => 'Antoine Gauvain', 'replace' => 'drlkf' },
      { 'attribute' => 'role', 'original' => 'Customer Solutions Engineer', 'replace' => 'CSE' }
    ]
  end

  def run
    lookup_table = QueryParser.empty_query(@people, %w(name role))
    @people.each do |person|
      matches = [{ attribute: 'name', keyword: person['name'] }]
      matches.push(attribute: 'role', keyword: person['role']) if @with_roles

      entry_table = QueryParser.index(person, matches: matches)
      lookup_table = QueryParser.merge(lookup_table, entry_table)
    end

    lookup_table = QueryParser.uniq(lookup_table)
    lookup_table = QueryParser.add_synonyms(lookup_table, @people, @synonyms)
    lookup_table = QueryParser.add_typos(lookup_table) if @with_typos
    lookup_table = QueryParser.uniq(lookup_table)

    options = {
      custom_ranking: 'order',
      searchable_attributes: %w(name)
    }
    options[:searchable_attributes].push('role') if @with_roles
    lookup_table = QueryParser.sort(lookup_table, options)

    facets = { '__EMPTY_QUERY__' => [] }
    facets = QueryParser.generate_facets(lookup_table, 'team', @people) if @with_facets

    css = CSSWriter.base
    css = CSSWriter.add_facet_counts(css, facets) if @with_facets
    css = CSSWriter.add_results(css, lookup_table, facets)

    main_css = File.read("#{@root}/public/css/base.css")
    final_css = main_css + css.join("\n")

    final_name = 'basic.css'
    final_name = 'typos.css' if @with_typos
    final_name = 'facets.css' if @with_facets
    final_name = 'roles.css' if @with_roles
    final_name = 'facets-typos.css' if @with_typos && @with_facets
    final_name = 'roles-typos.css' if @with_typos && @with_roles
    final_name = 'facets-roles.css' if @with_facets && @with_roles
    final_name = 'full.css' if @with_typos && @with_facets && @with_roles

    File.write("#{@root}/public/css/#{final_name}", final_css)
  end
end
Generate.new(ARGV).run
