#!/usr/bin/env ruby
require 'json'

# Generate a CSS file with rules for finding team members
class Generate
  def initialize
    @root = File.join(File.expand_path(File.dirname(__FILE__)), '..')
    people = JSON.parse(File.open("#{@root}/data/members.json").read)
    @people = people.map do |person|
      {
        name: person['name'],
        image: 'https://www.algolia.com/static_assets/images/' \
               "about-#{person['short_name']}.jpg"
      }
    end
  end

  def cloudinary_image(url)
    'https://res.cloudinary.com/pixelastic-parisweb/image/fetch/' \
    "w_50,h_50,q_90,c_scale,r_max,f_auto,e_grayscale/#{url}"
  end

  def run
    css = ['.searchbar + div:before { font-weight: bold; }']

    # Pre-loading all images
    preloaded_images = []
    @people.each do |person|
      preloaded_images.push("url(#{cloudinary_image(person[:image])})")
    end
    css.push('body:before{content:""; display:none; '\
             "background:#{preloaded_images.join(',')}}")

    @people.each do |person|
      name = person[:name].downcase
      start = 0
      max = name.length
      while start < max
        before = name[0..start]
        after = name[start + 1..-1]
        image = cloudinary_image(person[:image])

        css << ".searchbar[value='#{before}'] + div {"\
               "background-image: url(#{image}); }"
        css << ".searchbar[value='#{before}'] + div:before {"\
               "content: '#{before}'; }"
        css << ".searchbar[value='#{before}'] + div:after {"\
               "content: '#{after}'; }"
        start += 1
      end
    end

    File.write("#{@root}/public/generated.css", css.join("\n"))
  end
end
Generate.new.run
