#!/usr/bin/env ruby
require 'json'
require_relative '../lib/query_parser.rb'
require_relative '../lib/css_writer.rb'

# Generate a CSS file with rules for finding team members
class Generate
  def initialize
    @root = File.join(File.expand_path(File.dirname(__FILE__)), '..')
    people = JSON.parse(File.open("#{@root}/data/members.json").read)
    @people = people.map do |person|
      
      image = 'https://www.algolia.com/static_assets/images/' \
               "about-#{person['short_name']}.jpg"
      person['image'] = CSSWriter.cloudinary(image)
      person
    end

    @synonyms = {
      'Paul-Louis Nech' => %w(pl pln),
      'Matthieu Dumont' => %w(je jer jers jersk jerska),
      'Gianluca Bargelli' => %w(pi piz pizz pizza),
      'Antoine Gauvain' => %w(dr drl drlk drlkf),
      'Jan Petr' => %w(ho hon honz honza),
      'Tim Carry' => %w(cs css),
      'Xavier Grand' => %w(be bee beer),
      'Emily Hayman' => %w(fl fle flex flexb flexbo flexbox),
      'Rémy-Christophe Schermesser' => %w(rc rcs sc sca scal scala)
    }

    @with_typos = true
    @with_facets = true
  end

  def run
    lookup_table = QueryParser.empty_query(@people, 'name')
    @people.each do |person|
      entry_table = QueryParser.index(person, keyword: person['name'])
      lookup_table = QueryParser.merge(lookup_table, entry_table)
    end

    lookup_table = QueryParser.uniq(lookup_table)
    lookup_table = QueryParser.add_synonyms(lookup_table, @synonyms)
    lookup_table = QueryParser.add_typos(lookup_table) if @with_typos
    lookup_table = QueryParser.uniq(lookup_table)
    lookup_table = QueryParser.sort(lookup_table, 'order')

    facets = { '__EMPTY_QUERY__' => [] }
    facets = QueryParser.generate_facets(lookup_table, 'team', @people) if @with_facets

    css = CSSWriter.base
    css = CSSWriter.preload_images(css, @people)
    css = CSSWriter.add_facet_counts(css, facets) if @with_facets
    css = CSSWriter.add_results(css, lookup_table, facets)

    main_css = File.read("#{@root}/public/css/base.css")
    final_css = main_css + css.join("\n")

    final_name = 'basic.css'
    final_name = 'with-typos.css' if @with_typos
    final_name = 'with-facets.css' if @with_facets
    final_name = 'full.css' if @with_typos && @with_facets


    File.write("#{@root}/public/css/#{final_name}", final_css)
  end
end
Generate.new.run
