#!/usr/bin/env ruby
require 'shellwords'
require 'awesome_print'

# "Manual" minification as clean-css currently has a bug when it comes to minify
# case insensitive attributes matching
root = File.join(File.expand_path(File.dirname(__FILE__)), '..')
tmp = "#{root}/tmp/full.min.css"
min = "#{root}/public/css/full.min.css"

lines = File.open(tmp).read.split("\n")
regex = /(.*)(#i\[value=)(.*)(i\])(.*)/

new = []

lines.each do |line|
  # Rewrite font loading
  line.gsub!('public/fonts/', '../fonts/')

  matches = regex.match(line)
  # Skip if no match
  if matches.nil?
    new.push(line)
    next
  end
  prefix, input, value, icase, suffix = matches.captures
  value.delete!("'")
  new_line = "#{prefix}#{input}'#{value}' #{icase}#{suffix}"
  new.push(new_line)
end

File.write(min, new.join(''))
